/*
 * Self-host the base art the Craft › Planner shows (rings, amulets, belts, jewels). The CSP allows
 * images from *.poecdn.com only, and poecdn's signed URLs can't be built from a RePoE dds path, so
 * each base's `visual_identity.dds_file` is fetched ONCE from poe2db's CDN as webp into
 * src/assets/items/bases/ and a static-import map is written for the UI. Offline, never at deploy
 * time; commit the files it writes. Existing files are kept, so a re-run only fetches new art.
 * Run: npm run sync:base-art
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { loadCraftCatalog } from "../core/tools/craftmoves/catalog";
import { plannerCatalog } from "../core/tools/planner/load";
import { loadSnapshot } from "./repoe/snapshot";

const ART_DIR = join(process.cwd(), "src", "assets", "items", "bases");
const MAP_PATH = join(process.cwd(), "src", "components", "craft", "planner", "baseArtMap.ts");
const CDN = "https://cdn.poe2db.tw/image/";
const USER_AGENT = "poe2-coach-asset-sync/1.0 (one-time base art download)";
const DELAY_MS = 400;
// a base icon is a few KB; anything far larger is not the icon we asked for
const MAX_BYTES = 64 * 1024;

interface ArtJob {
  base: string;
  dds: string;
  file: string;
}

/** "Art/2DItems/Rings/Basetypes/BreachRing.dds" → "breach-ring.webp". */
function fileOf(dds: string): string {
  const stem = dds.split("/").at(-1)?.replace(/\.dds$/, "");
  if (!stem) throw new Error(`unexpected dds path: ${dds}`);
  return `${stem.replace(/_/g, "-").replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase()}.webp`;
}

function ddsOf(raw: unknown, base: string): string {
  if (typeof raw !== "object" || raw === null || !("visual_identity" in raw)) throw new Error(`${base}: no visual_identity in RePoE`);
  const vi = raw.visual_identity;
  if (typeof vi !== "object" || vi === null || !("dds_file" in vi) || typeof vi.dds_file !== "string") throw new Error(`${base}: no dds_file in RePoE`);
  return vi.dds_file;
}

function jobs(): ArtJob[] {
  const cat = loadCraftCatalog();
  const { repoe } = loadSnapshot();
  const byFile = new Map<string, string>();
  const out: ArtJob[] = [];
  for (const cls of plannerCatalog(cat).classes) {
    for (const b of cls.bases) {
      const id = cat.bases[b.name]?.id;
      if (!id) throw new Error(`${b.name}: not in the craft catalog`);
      const dds = ddsOf(repoe.base_items[id], b.name);
      const file = fileOf(dds);
      const seen = byFile.get(file);
      if (seen && seen !== dds) throw new Error(`art file name collision: ${seen} and ${dds} both map to ${file}`);
      byFile.set(file, dds);
      out.push({ base: b.name, dds, file });
    }
  }
  return out;
}

/** false when the CDN has no such file (403/404): that base keeps the class art, listed at the end. */
async function download(dds: string, file: string): Promise<boolean> {
  const url = `${CDN}${dds.replace(/\.dds$/, ".webp")}`;
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT }, signal: AbortSignal.timeout(30_000) });
  if (res.status === 403 || res.status === 404) {
    console.warn(`[base-art] MISSING ${url} → HTTP ${res.status}`);
    return false;
  }
  if (!res.ok) throw new Error(`base art fetch failed: ${url} → HTTP ${res.status}`);
  const type = res.headers.get("content-type") ?? "";
  if (!type.includes("image/webp")) throw new Error(`base art ${url} is ${type || "untyped"}, not webp`);
  const bytes = Buffer.from(await res.arrayBuffer());
  if (bytes.length === 0 || bytes.length > MAX_BYTES) throw new Error(`base art ${url} is ${bytes.length} bytes`);
  writeFileSync(join(ART_DIR, file), bytes);
  console.log(`[base-art] ${file} ← ${url} (${bytes.length} B)`);
  return true;
}

function writeMap(all: readonly ArtJob[]): void {
  const list = all.filter((j) => existsSync(join(ART_DIR, j.file)));
  const files = [...new Set(list.map((j) => j.file))].sort();
  const ident = new Map(files.map((f, i) => [f, `art${i}`]));
  const lines = [
    "// GENERATED by src/scripts/syncBaseArt.ts (npm run sync:base-art) — do not edit by hand.",
    "// Base name → self-hosted art (src/assets/items/bases, from RePoE visual_identity via poe2db).",
    ...files.map((f) => `import ${ident.get(f)} from "../../../assets/items/bases/${f}";`),
    "",
    "export const BASE_ART: Readonly<Record<string, string>> = {",
    ...[...list].sort((a, b) => a.base.localeCompare(b.base)).map((j) => `  ${JSON.stringify(j.base)}: ${ident.get(j.file)}.src,`),
    "};",
    "",
  ];
  writeFileSync(MAP_PATH, lines.join("\n"));
  console.log(`[base-art] wrote ${MAP_PATH} (${list.length} bases, ${files.length} files)`);
}

async function main(): Promise<void> {
  mkdirSync(ART_DIR, { recursive: true });
  mkdirSync(dirname(MAP_PATH), { recursive: true });
  const list = jobs();
  const pending = new Map(list.filter((j) => !existsSync(join(ART_DIR, j.file))).map((j) => [j.file, j.dds]));
  const missing: string[] = [];
  for (const [file, dds] of pending) {
    if (!(await download(dds, file))) missing.push(dds);
    await new Promise((r) => setTimeout(r, DELAY_MS));
  }
  writeMap(list);
  if (missing.length > 0) console.warn(`[base-art] ${missing.length} art file(s) not on the CDN — those bases show the class art:\n  ${missing.join("\n  ")}`);
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
