// GENERATED by src/scripts/syncBaseArt.ts (npm run sync:base-art) — do not edit by hand.
// Base name → self-hosted art (src/assets/items/bases, from RePoE visual_identity via poe2db).
import art0 from "../../../assets/items/bases/absent-amulet.webp";
import art1 from "../../../assets/items/bases/amber-amulet.webp";
import art2 from "../../../assets/items/bases/amethyst-ring.webp";
import art3 from "../../../assets/items/bases/azure-amulet.webp";
import art4 from "../../../assets/items/bases/belt01.webp";
import art5 from "../../../assets/items/bases/belt02.webp";
import art6 from "../../../assets/items/bases/belt03.webp";
import art7 from "../../../assets/items/bases/belt04.webp";
import art8 from "../../../assets/items/bases/belt05.webp";
import art9 from "../../../assets/items/bases/belt06.webp";
import art10 from "../../../assets/items/bases/belt07.webp";
import art11 from "../../../assets/items/bases/belt08.webp";
import art12 from "../../../assets/items/bases/belt09.webp";
import art13 from "../../../assets/items/bases/belt10.webp";
import art14 from "../../../assets/items/bases/belt11.webp";
import art15 from "../../../assets/items/bases/bloodstone-amulet.webp";
import art16 from "../../../assets/items/bases/breach-ring.webp";
import art17 from "../../../assets/items/bases/breachlord-ring-chayula.webp";
import art18 from "../../../assets/items/bases/breachlord-ring-esh.webp";
import art19 from "../../../assets/items/bases/breachlord-ring-formless.webp";
import art20 from "../../../assets/items/bases/breachlord-ring-tul.webp";
import art21 from "../../../assets/items/bases/breachlord-ring-uul-netol.webp";
import art22 from "../../../assets/items/bases/breachlord-ring-xoph.webp";
import art23 from "../../../assets/items/bases/corona-amulet.webp";
import art24 from "../../../assets/items/bases/crimson-amulet.webp";
import art25 from "../../../assets/items/bases/diamond-jewel.webp";
import art26 from "../../../assets/items/bases/emerald-jewel.webp";
import art27 from "../../../assets/items/bases/emerald-ring.webp";
import art28 from "../../../assets/items/bases/forking-belt.webp";
import art29 from "../../../assets/items/bases/gold-amulet.webp";
import art30 from "../../../assets/items/bases/gold-ring.webp";
import art31 from "../../../assets/items/bases/heist-amulet1.webp";
import art32 from "../../../assets/items/bases/heist-amulet2.webp";
import art33 from "../../../assets/items/bases/invoking-belt.webp";
import art34 from "../../../assets/items/bases/iron-ring.webp";
import art35 from "../../../assets/items/bases/jade-amulet.webp";
import art36 from "../../../assets/items/bases/lake-ring1.webp";
import art37 from "../../../assets/items/bases/lake-ring2.webp";
import art38 from "../../../assets/items/bases/lake-ring3.webp";
import art39 from "../../../assets/items/bases/lake-ring4.webp";
import art40 from "../../../assets/items/bases/lament-amulet.webp";
import art41 from "../../../assets/items/bases/lapis-amulet.webp";
import art42 from "../../../assets/items/bases/lazuli-ring.webp";
import art43 from "../../../assets/items/bases/lunar-amulet.webp";
import art44 from "../../../assets/items/bases/mirror-ring.webp";
import art45 from "../../../assets/items/bases/pearl-ring.webp";
import art46 from "../../../assets/items/bases/pearlescent-amulet.webp";
import art47 from "../../../assets/items/bases/portent-amulet.webp";
import art48 from "../../../assets/items/bases/prismatic-ring.webp";
import art49 from "../../../assets/items/bases/ruby-jewel.webp";
import art50 from "../../../assets/items/bases/ruby-ring.webp";
import art51 from "../../../assets/items/bases/sapphire-jewel.webp";
import art52 from "../../../assets/items/bases/sapphire-ring.webp";
import art53 from "../../../assets/items/bases/sinew-belt.webp";
import art54 from "../../../assets/items/bases/solar-amulet.webp";
import art55 from "../../../assets/items/bases/special-emerald-jewel.webp";
import art56 from "../../../assets/items/bases/special-ruby-jewel.webp";
import art57 from "../../../assets/items/bases/special-sapphire-jewel.webp";
import art58 from "../../../assets/items/bases/stalking-belt.webp";
import art59 from "../../../assets/items/bases/stellar-amulet.webp";
import art60 from "../../../assets/items/bases/timelost-diamond-jewel.webp";
import art61 from "../../../assets/items/bases/topaz-ring.webp";
import art62 from "../../../assets/items/bases/unset-ring.webp";

export const BASE_ART: Readonly<Record<string, string>> = {
  "Absent Amulet": art0.src,
  "Abyssal Signet": art34.src,
  "Amber Amulet": art1.src,
  "Amethyst Ring": art2.src,
  "Azure Amulet": art3.src,
  "Biostatic Ring": art20.src,
  "Bloodstone Amulet": art15.src,
  "Breach Ring": art16.src,
  "Corona Amulet": art23.src,
  "Crimson Amulet": art24.src,
  "Diamond": art25.src,
  "Double Belt": art11.src,
  "Dusk Amulet": art31.src,
  "Dusk Ring": art36.src,
  "Emerald": art26.src,
  "Emerald Ring": art27.src,
  "Fine Belt": art14.src,
  "Forking Belt": art28.src,
  "Gloam Amulet": art31.src,
  "Gloam Ring": art37.src,
  "Gold Amulet": art29.src,
  "Gold Ring": art30.src,
  "Grasping Ring": art19.src,
  "Heavy Belt": art12.src,
  "Invoking Belt": art33.src,
  "Iron Ring": art34.src,
  "Jade Amulet": art35.src,
  "Kinetic Ring": art21.src,
  "Lament Amulet": art40.src,
  "Lapis Amulet": art41.src,
  "Lazuli Ring": art42.src,
  "Linen Belt": art5.src,
  "Long Belt": art7.src,
  "Lunar Amulet": art43.src,
  "Mail Belt": art10.src,
  "Mnemonic Ring": art18.src,
  "Oneiric Ring": art17.src,
  "Ornate Belt": art9.src,
  "Pearl Ring": art45.src,
  "Pearlescent Amulet": art46.src,
  "Penumbra Amulet": art32.src,
  "Penumbra Ring": art38.src,
  "Plate Belt": art8.src,
  "Portent Amulet": art47.src,
  "Prismatic Ring": art48.src,
  "Rawhide Belt": art4.src,
  "Refined Breach Ring": art16.src,
  "Ring": art44.src,
  "Ruby": art49.src,
  "Ruby Ring": art50.src,
  "Runemastered Heavy Belt": art12.src,
  "Runemastered Veridical Chain": art15.src,
  "Sapphire": art51.src,
  "Sapphire Ring": art52.src,
  "Sinew Belt": art53.src,
  "Solar Amulet": art54.src,
  "Stalking Belt": art58.src,
  "Stellar Amulet": art59.src,
  "Tenebrous Amulet": art32.src,
  "Tenebrous Ring": art39.src,
  "Time-Lost Diamond": art60.src,
  "Time-Lost Emerald": art55.src,
  "Time-Lost Ruby": art56.src,
  "Time-Lost Sapphire": art57.src,
  "Topaz Ring": art61.src,
  "Two-Stone Ring": art34.src,
  "Unset Ring": art62.src,
  "Utility Belt": art13.src,
  "Veridical Chain": art15.src,
  "Vitalic Ring": art22.src,
  "Wide Belt": art6.src,
};
